# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'  # Ensure consistency with platform version
      config.build_settings['ENABLE_BITCODE'] = 'NO'  # Disable Bitcode globally
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
    end
    flutter_additional_ios_build_settings(target)
  end

  # Dynamic Bitcode Stripping
  bitcode_strip_path = `xcrun --find bitcode_strip`.strip

  def strip_bitcode_from_framework(bitcode_strip_path, framework_binary)
    if File.exist?(framework_binary)
      command = "#{bitcode_strip_path} #{framework_binary} -r -o #{framework_binary}"
      puts "Stripping Bitcode from: #{framework_binary}"
      system(command)
    end
  end

  # Find and strip Bitcode from all frameworks
  Dir.glob("Pods/**/*.framework").each do |framework|
    binary_name = File.basename(framework, ".framework")
    binary_path = "#{framework}/#{binary_name}"
    strip_bitcode_from_framework(bitcode_strip_path, binary_path)
  end
end